### PR TITLE
Periodic boundary conditions for radial SFs

### PR DESCRIPTION
**Pull request by mgastegger**
Partial fix for SFs with periodic boundary conditions in issue #104.
Angular functions currently in work.

### CODE REVIEW

**Comment by ktschuett** [comment]
@Stefaanhess Could you check whether this is properly tested?

**Comment by ktschuett** [comment]
@mgastegger I merged the angular stuff, but test are still failing.

**Comment by lmj1029123** [comment]
I think for this one, instead of having

```
distances = snn.atom_distances(
                positions, neighbors, neighbor_mask=neighbor_mask,
)
radial_sf = self.RDF(
                distances, elemental_weights=Z_ij, neighbor_mask=neighbor_mask,
                cell=cell, cell_offsets=cell_offset
            )
```

we should have 

```
 distances = snn.atom_distances(
                positions, neighbors, neighbor_mask=neighbor_mask,
                cell=cell, cell_offsets=cell_offset
            )
            radial_sf = self.RDF(
                distances, elemental_weights=Z_ij, neighbor_mask=neighbor_mask
            )
```
The second version has already been done in the angular fix.

**Comment by mgastegger** [comment]
Thanks, already spotted it.

**Pull request merged**
